name: test_and_build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Architecture Benchmark Test
      run: |
        python -m enhancer_toch.demucs
        
    - name: Test Enhance
      run: python -m enhancer_toch.enhance --dns48 --noisy_dir dataset/debug/noisy/
  
    - name: Test Training
      run: |	
        sh make_debug.sh
        python train.py num_workers=0 device=cpu epochs=1 dset.test= demucs.hidden=1 demucs.depth=3	
    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U .

    - name: Build package
      run: |
        python setup.py bdist_wheel

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.0.0
      if: github.ref == 'refs/heads/main'
      with:
        name: python-package-3.7-ubuntu-latest
        path: dist/*.whl
        retention-days: 10
